import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Long-form Video Generator | Virlo",
};

export default function LongForm() {
  return (
    <div style={{ maxWidth: "960px", margin: "0 auto", padding: "2rem 1.5rem" }}>
      <div style={{ fontSize: "11px", fontFamily: "Syne, sans-serif", fontWeight: 700, letterSpacing: "2px", color: "var(--accent2)", textTransform: "uppercase", marginBottom: "1rem" }}>
        Documentaries & VSLs
      </div>
      <h1 style={{ fontSize: "2.5rem", fontWeight: 800, letterSpacing: "-1px", marginBottom: "1.5rem" }}>
        Long-form Video Engine
      </h1>
      <p style={{ color: "var(--muted)", maxWidth: "600px", marginBottom: "3rem", fontSize: "1.05rem" }}>
        Scene-by-scene Native 4K rendering means absolutely zero quality degradation. A 10-minute documentary looks as perfectly sharp as a 10-second ad.
      </p>

      {/* Feature grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "1.25rem", marginBottom: "3rem" }}>
        <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "14px", padding: "1.5rem" }}>
          <div style={{ fontSize: "1.5rem", marginBottom: "1rem" }}>📋</div>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: ".5rem" }}>Smart Storyboard</h3>
          <p style={{ fontSize: ".85rem", color: "var(--muted)", lineHeight: 1.6 }}>Topic + duration → full scene breakdown. Each scene gets a specific motion prompt, voiceover, and music mood generated by our Intelligence Core.</p>
        </div>
        <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "14px", padding: "1.5rem" }}>
          <div style={{ fontSize: "1.5rem", marginBottom: "1rem" }}>🎥</div>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: ".5rem" }}>Scene-by-Scene Render</h3>
          <p style={{ fontSize: ".85rem", color: "var(--muted)", lineHeight: 1.6 }}>Each 30s scene renders independently in cinematic 4K resolution. Say goodbye to blurry minute-five artifacts and degrading quality.</p>
        </div>
        <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "14px", padding: "1.5rem" }}>
          <div style={{ fontSize: "1.5rem", marginBottom: "1rem" }}>⚙️</div>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: ".5rem" }}>Seamless Assembly</h3>
          <p style={{ fontSize: ".85rem", color: "var(--muted)", lineHeight: 1.6 }}>Our dedicated post-processing engine handles seamless transitions, audio ducking, and global captioning automatically.</p>
        </div>
      </div>

      {/* Generator UI */}
      <div style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "16px", padding: "2rem" }}>
        <h2 style={{ fontSize: "1.1rem", fontWeight: 700, marginBottom: "1.5rem" }}>Generate Storyboard</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          {/* Prompt (Topic) - comes first */}
          <div>
            <label style={{ display: "block", fontSize: "0.9rem", fontWeight: "600", color: "var(--text)", marginBottom: "0.5rem" }}>
              Topic/Prompt
            </label>
            <input
              type="text"
              placeholder="e.g. The history of mechanical keyboards and their evolution..."
              style={{
                width: "100%",
                background: "var(--bg)",
                border: "1px solid var(--border)",
                borderRadius: "8px",
                padding: "1rem",
                color: "var(--text)",
                fontSize: "0.9rem",
                outline: "none",
                fontFamily: "DM Sans, sans-serif",
              }}
            />
          </div>

          {/* Description - comes second */}
          <div>
            <label style={{ display: "block", fontSize: "0.9rem", fontWeight: "600", color: "var(--text)", marginBottom: "0.5rem" }}>
              Description (Optional)
            </label>
            <textarea
              placeholder="Provide additional context, key points to cover, or specific requirements..."
              rows={3}
              style={{
                width: "100%",
                background: "var(--bg)",
                border: "1px solid var(--border)",
                borderRadius: "8px",
                padding: "1rem",
                color: "var(--text)",
                fontSize: "0.9rem",
                outline: "none",
                fontFamily: "DM Sans, sans-serif",
                resize: "vertical",
              }}
            />
          </div>

          {/* Duration and Generate button */}
          <div style={{ display: "flex", gap: "1rem", alignItems: "flex-end" }}>
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: "0.9rem", fontWeight: "600", color: "var(--text)", marginBottom: "0.5rem" }}>
                Duration
              </label>
              <select style={{
                width: "100%",
                background: "var(--bg)",
                border: "1px solid var(--border)",
                borderRadius: "8px",
                padding: "1rem",
                color: "var(--text)",
                fontSize: "0.9rem",
                outline: "none",
                fontFamily: "DM Sans, sans-serif",
              }}>
                <option value="2">2 minutes</option>
                <option value="5">5 minutes</option>
                <option value="10">10 minutes</option>
              </select>
            </div>
            <button style={{
              background: "var(--accent)",
              color: "#fff",
              border: "none",
              borderRadius: "8px",
              padding: "1rem 2rem",
              fontWeight: 700,
              cursor: "pointer",
              fontFamily: "Syne, sans-serif",
              fontSize: "0.9rem",
            }}>
              Generate Storyboard
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
